CREATE DATABASE CLASE_1_4;

USE CLASE_1_4;

CREATE TABLE EMPLEADOS
(
    ID_EMPLEADO               INT         NOT NULL,
    NOMBRE_EMPLEADO           VARCHAR(50) NOT NULL,
    SEXO_EMPLEADO             CHAR,
    FECHA_NACIMIENTO_EMPLEADO DATE        NOT NULL,
    SALARIO_EMPLEADO          DOUBLE      NOT NULL,
    COMISION_EMPLEADO         DOUBLE      NOT NULL,
    CARGO_EMPLEADO            VARCHAR(50) NOT NULL,
    ID_JEFE                   INT,
    ID_DEPARTAMENTO           INT,
    PRIMARY KEY (ID_EMPLEADO),
    FOREIGN KEY (ID_JEFE) REFERENCES EMPLEADOS (ID_EMPLEADO),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS (ID_DEPARTAMENTO)
);

CREATE TABLE DEPARTAMENTOS
(
    ID_DEPARTAMENTO     INT         NOT NULL,
    NOMBRE_DEPARTAMENTO VARCHAR(50) NOT NULL,
    CIUDAD              VARCHAR(50) NOT NULL,
    ID_DIRECTOR         INT         NOT NULL,
    PRIMARY KEY (ID_DEPARTAMENTO),
    CONSTRAINT FK_ID_DIRECTOR FOREIGN KEY (ID_DIRECTOR) REFERENCES EMPLEADOS (ID_EMPLEADO)
);


INSERT INTO EMPLEADOS(ID_EMPLEADO, NOMBRE_EMPLEADO, SEXO_EMPLEADO, FECHA_NACIMIENTO_EMPLEADO, SALARIO_EMPLEADO,
                      COMISION_EMPLEADO, CARGO_EMPLEADO, ID_JEFE, ID_DEPARTAMENTO)
VALUES(1, 'MARCELO', 'M', '12-1-1970', 90000, 4000, 'ENCARGADO', 1, 1)


# 1. Obtener los datos completos de los empleados.
SELECT *
FROM EMPLEADOS;
# 2. Listar el nombre de los departamentos.
SELECT NOMBRE_DEPARTAMENTO
FROM DEPARTAMENTOS;
# 3. Obtener el nombre y cargo de todos los empleados, ordenado por salario.
SELECT NOMBRE_EMPLEADO, CARGO_EMPLEADO, SALARIO_EMPLEADO
FROM EMPLEADOS
ORDER BY SALARIO_EMPLEADO;
# 4. Obtener la lista de los empleados que ganan una comisión superior a su sueldo.
SELECT NOMBRE_EMPLEADO, SALARIO_EMPLEADO, COMISION_EMPLEADO
FROM EMPLEADOS
WHERE COMISION_EMPLEADO > SALARIO_EMPLEADO;
# 5. Listar los empleados cuya comisión es menor o igual que el 30% de su sueldo.
SELECT NOMBRE_EMPLEADO, SALARIO_EMPLEADO, COMISION_EMPLEADO
FROM EMPLEADOS
WHERE COMISION_EMPLEADO <= (SALARIO_EMPLEADO * 0.30);
# 6. Muestra los empleados cuyo nombre empiece entre las letras J y Z (rango). Liste estos empleados y su cargo por orden alfabético.
SELECT NOMBRE_EMPLEADO, CARGO_EMPLEADO
FROM EMPLEADOS
WHERE NOMBRE_EMPLEADO LIKE '[J-Z]%';
# 7. Hallar los empleados cuyo nombre no contiene la cadena “MA”
SELECT NOMBRE_EMPLEADO
FROM EMPLEADOS
WHERE NOMBRE_EMPLEADO NOT LIKE '%MA%';

# 8. Listar los datos de los empleados cuyo nombre inicia por la letra ‘M’, su salario es mayor a $800.000 o reciben comisión y trabajan para el departamento de ‘VENTAS’
SELECT NOMBRE_EMPLEADO, SALARIO_EMPLEADO, NOMBRE_DEPARTAMENTO FROM EMPLEADOS, DEPARTAMENTOS
WHERE NOMBRE_EMPLEADO LIKE 'M%' AND
      SALARIO_EMPLEADO > 800000
   OR COMISION_EMPLEADO > 0 AND NOMBRE_DEPARTAMENTO = 'VENTAS';
# 9. Mostrar el salario más alto de la empresa.
SELECT SALARIO_EMPLEADO
FROM EMPLEADOS
ORDER BY SALARIO_EMPLEADO
LIMIT 1;
# 10. Hallar el salario más alto, el más bajo y la diferencia entre ellos.
SELECT (SELECT SALARIO_EMPLEADO FROM EMPLEADOS ORDER BY SALARIO_EMPLEADO LIMIT 1)
           - (
           SELECT SALARIO_EMPLEADO FROM EMPLEADOS ORDER BY SALARIO_EMPLEADO DESC LIMIT 1);

# 11. Mostrar el número de empleados de sexo femenino y de sexo masculino, por departamento.
SELECT COUNT(SEXO_EMPLEADO)
FROM EMPLEADOS, DEPARTAMENTOS
WHERE SEXO_EMPLEADO = 'F'
   OR SEXO_EMPLEADO = 'M' AND EMPLEADOS.ID_DEPARTAMENTO = DEPARTAMENTOS.ID_DEPARTAMENTO GROUP BY DEPARTAMENTOS.ID_DEPARTAMENTO;

# 12. Hallar los departamentos que tienen más de tres empleados. Mostrar el número de empleados de esos departamentos.
SELECT NOMBRE_DEPARTAMENTO, COUNT(ID_EMPLEADO)
FROM DEPARTAMENTOS,
     EMPLEADOS
WHERE DEPARTAMENTOS.ID_DEPARTAMENTO = EMPLEADOS.ID_DEPARTAMENTO;

# 13. Mostrar el código y nombre de cada jefe, junto al número de empleados que dirige. Solo los que tengan más de dos empleados (2 incluido).


# 14. Hallar los departamentos que no tienen empleados
SELECT NOMBRE_DEPARTAMENTO
FROM DEPARTAMENTOS,
     EMPLEADOS
WHERE DEPARTAMENTOS.ID_DEPARTAMENTO = EMPLEADOS.ID_DEPARTAMENTO
GROUP BY DEPARTAMENTOS.ID_DEPARTAMENTO
HAVING COUNT(EMPLEADOS.ID_EMPLEADO) = 0;

# 15. Mostrar el nombre del departamento cuya suma de salarios sea la más alta, indicando el valor de
# la suma.

SELECT NOMBRE_DEPARTAMENTO, SALARIO_EMPLEADO
FROM DEPARTAMENTOS,
     EMPLEADOS
WHERE DEPARTAMENTOS.ID_DEPARTAMENTO = EMPLEADOS.ID_DEPARTAMENTO
GROUP BY SALARIO_EMPLEADO DESC
LIMIT 1;